### PR TITLE
Add SUSE support

### LINKED ISSUE #209: Add SUSE support
### :speaking_head: Foreword

It would be nice to add SUSE Linux support. I've noticed its support was listed in earlier cookbook releases. Also, there are parts of code that are designed for use with SUSE. However, I wasn't able to run this cookbook with SLES 12.5, Splunk installation was failing due to a [bug](https://github.com/chef/chef/issues/11638) in zypper_package resource. It's not hard to fix this bug on cookbook's side, so I can provide a pull request with the fix. At the same time, I will need someone's help with adding test suites for SUSE and maybe some other adjustments to the cookbook itself since it consists of a lot of code I'm not familiar with.

## ☹️  Problem Statement

This cookbook supported SUSE, and there is lots of code blocks that should provide this support, so it would be good to finalize the support and make this cookbook work with SUSE.

## :grey_question: Possible Solution

I provide a pull request that enables support of SLES. The maintainers help with setting up tests for other SUSE distribution.

## :arrow_heading_up: Describe alternatives you've considered

I might use other Linux distro, but it's not a good solution for me.

## :heavy_plus_sign: Additional context

- Possible bug in zypper_package resource that generates incorrect command and make installation of RPM impossible: https://github.com/chef/chef/issues/11638

### PR DESCRIPTION
**Pull request by vzabawski**
# Description

Override package manager resource for SUSE to make it possible to use the cookbook with such distro.

## Issues Resolved

#209

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Review by ramereth — CHANGES_REQUESTED** [review]
Can you please add the `opensuse-leap-15` platform the both kitchen ymls and also to `.github/workflows/ci.yml` so that it runs in CI for testing? Also rebase and update against the master branch.

**Comment by vzabawski** [comment]
Done. I also updated readme and metadata.rb to reflect changes.

**Comment by ramereth** [comment]
@vzabawski we made some recent changes to this main branch of this cookbook, can you please rebase and push it back up?

**Comment by vzabawski** [comment]
Hi @ramereth. Any updates on this PR?

**Review by ramereth — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [9.1.0](https://github.com/sous-chefs/chef-splunk/releases/tag/9.1.0)

**Pull request merged**
